In [1]:
import pandas as pd

In [14]:
word_count_data = pd.read_csv('word_count.csv')

In [15]:
df_word_count = pd.DataFrame(word_count_data)

In [16]:
df_word_count

                handle     Word  Count
0      AustinScottGA08    today    496
1      AustinScottGA08    thank    361
2      AustinScottGA08  georgia    292
3      AustinScottGA08      day    276
4      AustinScottGA08     more    274
...                ...      ...    ...
26745     virginiafoxx     call     94
26746     virginiafoxx    small     92
26747     virginiafoxx     here     91
26748     virginiafoxx       so     91
26749     virginiafoxx     read     90

[26750 rows x 3 columns]

In [17]:
basic_info = pd.read_csv('reptweets.csv')

In [18]:
df_basic_info = pd.DataFrame(basic_info)

In [19]:
df_basic_info

                   name            handle state  party   branch
0         Baldwin, Tammy   SenatorBaldwin     WI      D  Senate
1         Barrasso, John  SenJohnBarrasso     WY      R  Senate
2     Bennet, Michael F.    SenatorBennet     CO      D  Senate
3      Blackburn, Marsha  MarshaBlackburn     TN      R  Senate
4    Blumenthal, Richard    SenBlumenthal     CT      D  Senate
..                   ...              ...    ...    ...     ...
531   Wittman, Robert J.       RobWittman     VA      R   House
532        Womack, Steve  rep_stevewomack     AR      R   House
533          Yakym, Rudy        RudyYakym     IN      R   House
534     Yarmuth, John A.   RepJohnYarmuth     KY      D   House
535          Zeldin, Lee     RepLeeZeldin     NY      R   House

[536 rows x 5 columns]

In [22]:
df_democrats = df_basic_info.loc[df_basic_info['party'] == "D"]

KeyError: 'party'